### ISSUE TITLE
separator参数无效

### ISSUE THREAD

**Issue by yudan215** [PanJiaChen/vue-countTo#16]
按照[官网DEMO](http://panjiachen.github.io/countTo/demo/)
separator 加了冒号会报错,不加会无效

`<count-to :start-val="0" :end-val="25" :duration="2600" :separator="" class="box-num"/>`

**Comment by CucurbitBaby** [comment]
就报错

**Comment by CucurbitBaby** [comment]
:separator="null"  解决问题 或者在data中定义一个替换符的属性空值
