### ISSUE TITLE
自动播放的问题

### ISSUE THREAD

**Issue by LoverMaker** [PanJiaChen/vue-countTo#3]
endVal变化时，需要手动调用start来启动动画。
建议在autoplay时, watch endVal自动开启动画

**Comment by PanJiaChen** [comment]
这我感觉还是手动更灵活一些，很多场景其实并不需要val 一发生变化就需要autoplay

**Comment by PanJiaChen** [comment]
@LoverMaker 思考了一下，我觉得你的建议很对，在新版本v1.0.11已watch startVal or endVal 的变化，会自动开启动画
