### ISSUE TITLE
make update possible

### ISSUE THREAD

**Issue by appinteractive** [PanJiaChen/vue-countTo#5]
would be very nice to be able to update the values without the need to manually change both the start end endval. 

In my setup I have a vote mechanism where I display several options with percentage values. Anytime a user votes, the values update automatically. The issue with this component is that I can't update the values from its current values (like from 50 to 80 percent) without braking it. Any Idea how to manage that usecase?

<img width="565" alt="grafik" src="https://user-images.githubusercontent.com/432828/30032817-32770f84-9198-11e7-8937-e94e3f4a1191.png">

By the way, thanks for that cool component. Keep up the good workd ;)

**Comment by PanJiaChen** [comment]
now v1.0.11 can solve this problem.
when autoplay:true , it will auto restart when endVal or startVal change.
and you problem you see the [demo](http://panjiachen.github.io/countTo/demo/)   `incremental update`
you can just set `starVal=endVal` and `endVal to what you watch`

**Comment by appinteractive** [comment]
Thanks man! Works like a charm 👍
