### ISSUE TITLE
不能显示小数点哦。。。

### ISSUE THREAD

**Issue by qingbopro** [PanJiaChen/vue-countTo#6]
不能显示小数点哦。。。
而且会多出来一个无用的span元素。。。
可以改造一下吗

**Comment by PanJiaChen** [comment]
要手动设置 小数点精确位数
如： `:decimals=2`

**Comment by qingbopro** [comment]
奥，看到了谢谢，要是支持传字符串就完美了，后台传来的数据是'1,234.23'这种的话，我还要Number(num.replace(/,/g,''))

**Comment by PanJiaChen** [comment]
这种还是自已formar一下比较好，组件来做的话要考虑的情况太多了
