### ISSUE TITLE
About `autoplay`

### ISSUE THREAD

**Issue by zjuwujunchao** [PanJiaChen/vue-countTo#7]
`<count-to :startVal='0' :endVal='reportCount'></count-to>`

```  
created () {
   axios.get('/api/admin/report/count')
     .then(response => {
       this.reportCount = response.data.reportCount
     })
}
```

以上组件会在加载时自动开始向 2017 (默认值) 计数, 即使数据请求尚未返回.

`<count-to :startVal='0' :endVal='reportCount' :autoplay='false'></count-to>`

这样需要手动触发计数很不方便.

`<count-to :startVal='0' :endVal='reportCount'></count-to>`

```  
data () {
  reportCount: 0
}
```

这样其实会在加载时开始计数, 只不过一直是 0, 如果数据返回有延迟, 计数值会出现跳跃.

Workaround:

`<count-to :startVal='0' :endVal='reportCount' :autoplay="true" v-if="typeof reportCount !== 'undefined'"></count-to>`

这样可以使组件在请求返回后才开始加载.

---

我向 CountTo 组件添加了一个参数 `autoplayWhenChange`

```
props: {
  autoplayWhenChange: {
    type: Boolean,
    required: false,
    default: true
  }
}
```

并修改监视器

```
watch: {
  startVal () {
    if (this.autoplay || this.autoplayWhenChange) {
      this.start()
    }
  },
  endVal () {
    if (this.autoplay || this.autoplayWhenChange) {
      this.start()
    }
  }
}
```

`<count-to :startVal='0' :endVal='reportCount' :autoplay="false" :autoplayWhenChange="true"></count-to>`

这样可以实现在请求返回后开始计数, 同时避免数字不连续的跳跃.

这样不知道是不是一个合理的 feature.

**Comment by PanJiaChen** [comment]
```
<count-to :startVal='0' :endVal='reportCount'></count-to>

data () {
  reportCount: 0
}
```
其实我觉得这样设置是很合理的，再增加一个参数只会增加使用成本。
而且现有参数也已经可以满足你的需求了

![image](https://user-images.githubusercontent.com/8121621/32874119-ce8767f2-ca55-11e7-9d84-1525e105687c.png)


 `:autoplay="false"` 你可以设置 `autoplay` 为 `false`, 当异步拿到 `reportCount`
 之后 手动开始count
如：
```
<count-to :startVal='0' :endVal='reportCount' :autoplay='false' ref='countTo'></count-to>

this.$refs.countTo.start()
```

**Comment by zjuwujunchao** [comment]
OK 😄
