### ISSUE TITLE
场景：递增，ease: fasle 的时候，数值不变化

### ISSUE THREAD

**Issue by uncleLian** [PanJiaChen/vue-countTo#9]
看了代码发现是这里写错了this.printVal = this.localStartVal + (this.localStartVal - this.startVal) * (progress / this.localDuration)
改为：this.printVal = this.localStartVal + (this.endVal - this.localStartVal) * (progress / this.localDuration) 运行正常

**Comment by PanJiaChen** [comment]
谢谢的支持，能提一个pr么？

**Comment by uncleLian** [comment]
好的 稍等
